const ACTION_TYPES = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  AUTH_ERROR: 'AUTH_ERROR',
  AUTH_SUCCESS: 'AUTH_SUCCESS',

  LOAD_ALL_CHATS_REQUEST:"LOAD_ALL_CHATS_REQUEST",
  LOAD_ALL_CHATS_SUCCESS: "LOAD_ALL_CHATS_SUCCESS",
  LOAD_ALL_CHATS_ERROR: "LOAD_ALL_CHATS_ERROR",

  SELECT_CHAT_ACTION: 'SELECT_CHAT_ACTION',

  CREATE_CHAT_REQUEST: "CREATE_CHAT_REQUEST",
  CREATE_CHAT_SUCCESS: "CREATE_CHAT_SUCCESS",
  CREATE_CHAT_ERROR: "CREATE_CHAT_ERROR",


  NEW_CHAT_MESSAGES: 'LOAD_CHAT_MESSAGES_SUCCESS',


  JOIN_TO_CHATS_REQUEST: "JOIN_TO_CHAT_REQUEST",
  JOIN_TO_CHATS_SUCCESS: "JOIN_TO_CHAT_SUCCESS",
  JOIN_TO_CHATS_ERROR: "JOIN_TO_CHAT_ERROR",
  ADD_CHAT: "ADD_CHAT",


};

export default ACTION_TYPES;